import json

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# 🚀 Multi-SOTA Benchmarking & Real-Time Profiling\n",
            "\n",
            "This notebook compares the **Hybrid CNN-QNN** against 4 State-of-the-Art models:\n",
            "- **YOLOv8-cls (Nano)**: Real-time industry standard.\n",
            "- **MobileNetV3-Small**: Optimized for drones and edge computing.\n",
            "- **EfficientNet-B0**: High accuracy, tiny footprint.\n",
            "- **ResNet18**: The classic baseline.\n",
            "\n",
            "We also include extensive visualizations: Radar charts, SHAP values, ROC curves, and prediction heatmaps."
        ]
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "source": [
            "import os\n",
            "import time\n",
            "import torch\n",
            "import torch.nn as nn\n",
            "import torch.optim as optim\n",
            "import torchvision.transforms as transforms\n",
            "import torchvision.models as models\n",
            "import pennylane as qml\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "from torch.utils.data import DataLoader, Dataset\n",
            "from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, roc_curve, precision_recall_curve\n",
            "from PIL import Image\n",
            "import kagglehub\n",
            "import warnings\n",
            "import scikit_posthocs as sp\n",
            "import shap\n",
            "from ultralytics import YOLO\n",
            "\n",
            "warnings.filterwarnings('ignore')\n",
            "plt.style.use('seaborn-v0_8-darkgrid')"
        ],
        "execution_count": None
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"Downloading dataset...\")\n",
            "path = kagglehub.dataset_download(\"aminelaatam/weed-classification\")\n",
            "DATA_DIR = os.path.join(path, \"CornWeed\")\n",
            "\n",
            "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
            "print(f\"Using device: {device}\")\n",
            "\n",
            "transform = transforms.Compose([\n",
            "    transforms.Resize((128, 128)),\n",
            "    transforms.ToTensor(),\n",
            "    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n",
            "])\n",
            "\n",
            "class CornWeedDataset(Dataset):\n",
            "    def __init__(self, root_dir, transform=None):\n",
            "        self.root_dir = root_dir\n",
            "        self.transform = transform\n",
            "        self.images = []\n",
            "        self.labels = []\n",
            "        self.class_map = {\"Corn\": 0, \"Weed\": 1}\n",
            "        \n",
            "        for class_name in os.listdir(root_dir):\n",
            "            class_path = os.path.join(root_dir, class_name)\n",
            "            if os.path.isdir(class_path):\n",
            "                for img_name in os.listdir(class_path):\n",
            "                    if img_name.endswith(('.jpg', '.png', '.jpeg')):\n",
            "                        self.images.append(os.path.join(class_path, img_name))\n",
            "                        self.labels.append(self.class_map.get(class_name.title(), -1))\n",
            "                        \n",
            "        valid = [i for i, l in enumerate(self.labels) if l != -1]\n",
            "        self.images = [self.images[i] for i in valid]\n",
            "        self.labels = [self.labels[i] for i in valid]\n",
            "\n",
            "    def __len__(self): return len(self.images)\n",
            "    def __getitem__(self, idx):\n",
            "        img = Image.open(self.images[idx]).convert(\"RGB\")\n",
            "        if self.transform: img = self.transform(img)\n",
            "        return img, self.labels[idx]\n",
            "\n",
            "train_dataset = CornWeedDataset(os.path.join(DATA_DIR, \"train\"), transform=transform)\n",
            "test_dataset = CornWeedDataset(os.path.join(DATA_DIR, \"test\"), transform=transform)\n",
            "\n",
            "train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)\n",
            "test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)"
        ],
        "execution_count": None
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "source": [
            "def count_parameters(model):\n",
            "    return sum(p.numel() for p in model.parameters() if p.requires_grad)\n",
            "\n",
            "def measure_fps(model, dataloader, device, is_yolo=False):\n",
            "    if is_yolo:\n",
            "        return 0 # Handled separately\n",
            "    \n",
            "    model.eval()\n",
            "    dummy_input = torch.randn(1, 3, 128, 128).to(device)\n",
            "    with torch.no_grad():\n",
            "        for _ in range(10): model(dummy_input)\n",
            "        if torch.cuda.is_available(): torch.cuda.synchronize()\n",
            "        \n",
            "    start_time = time.perf_counter()\n",
            "    total_images = 0\n",
            "    with torch.no_grad():\n",
            "        for images, _ in dataloader:\n",
            "            images = images.to(device)\n",
            "            _ = model(images)\n",
            "            total_images += images.size(0)\n",
            "    if torch.cuda.is_available(): torch.cuda.synchronize()\n",
            "    end_time = time.perf_counter()\n",
            "    return total_images / (end_time - start_time)"
        ],
        "execution_count": None
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "source": [
            "n_qubits = 4\n",
            "dev = qml.device(\"default.qubit\", wires=n_qubits)\n",
            "\n",
            "@qml.qnode(dev, interface=\"torch\")\n",
            "def quantum_circuit(inputs, weights):\n",
            "    qml.AngleEmbedding(inputs, wires=range(n_qubits))\n",
            "    qml.StronglyEntanglingLayers(weights, wires=range(n_qubits))\n",
            "    return [qml.expval(qml.PauliZ(i)) for i in range(n_qubits)]\n",
            "\n",
            "quantum_layer = qml.qnn.TorchLayer(quantum_circuit, {\"weights\": (2, n_qubits, 3)})\n",
            "\n",
            "class HybridCNNQNN(nn.Module):\n",
            "    def __init__(self):\n",
            "        super().__init__()\n",
            "        self.features = nn.Sequential(\n",
            "            nn.Conv2d(3, 32, 3, 1, 1), nn.ReLU(), nn.MaxPool2d(2, 2),\n",
            "            nn.Conv2d(32, 64, 3, 1, 1), nn.ReLU(), nn.MaxPool2d(2, 2)\n",
            "        )\n",
            "        self.fc1 = nn.Linear(64 * 32 * 32, n_qubits)\n",
            "        self.quantum = quantum_layer\n",
            "        self.fc2 = nn.Linear(n_qubits, 2)\n",
            "\n",
            "    def forward(self, x):\n",
            "        x = self.features(x)\n",
            "        x = x.view(x.size(0), -1)\n",
            "        x = torch.tanh(self.fc1(x))\n",
            "        x = self.quantum(x)\n",
            "        return self.fc2(x)\n",
            "\n",
            "hybrid_model = HybridCNNQNN().to(device)"
        ],
        "execution_count": None
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "source": [
            "resnet = models.resnet18(weights='DEFAULT')\n",
            "resnet.fc = nn.Linear(resnet.fc.in_features, 2)\n",
            "resnet = resnet.to(device)\n",
            "\n",
            "mobilenet = models.mobilenet_v3_small(weights='DEFAULT')\n",
            "mobilenet.classifier[3] = nn.Linear(mobilenet.classifier[3].in_features, 2)\n",
            "mobilenet = mobilenet.to(device)\n",
            "\n",
            "efficientnet = models.efficientnet_b0(weights='DEFAULT')\n",
            "efficientnet.classifier[1] = nn.Linear(efficientnet.classifier[1].in_features, 2)\n",
            "efficientnet = efficientnet.to(device)"
        ],
        "execution_count": None
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "source": [
            "def train_model(model, name, epochs=5):\n",
            "    print(f\"\\nTraining {name}...\")\n",
            "    criterion = nn.CrossEntropyLoss()\n",
            "    optimizer = optim.Adam(model.parameters(), lr=0.001)\n",
            "    \n",
            "    history = {'loss': [], 'acc': []}\n",
            "    for epoch in range(epochs):\n",
            "        model.train()\n",
            "        running_loss = 0.0\n",
            "        correct = 0\n",
            "        total = 0\n",
            "        for images, labels in train_loader:\n",
            "            images, labels = images.to(device), labels.to(device)\n",
            "            optimizer.zero_grad()\n",
            "            outputs = model(images)\n",
            "            loss = criterion(outputs, labels)\n",
            "            loss.backward()\n",
            "            optimizer.step()\n",
            "            \n",
            "            running_loss += loss.item()\n",
            "            _, pred = torch.max(outputs, 1)\n",
            "            correct += (pred == labels).sum().item()\n",
            "            total += labels.size(0)\n",
            "            \n",
            "        acc = correct / total\n",
            "        history['loss'].append(running_loss / len(train_loader))\n",
            "        history['acc'].append(acc)\n",
            "        print(f\"Epoch {epoch+1}/{epochs} - Acc: {acc:.4f}\")\n",
            "    \n",
            "    model.eval()\n",
            "    all_preds, all_labels, all_probs = [], [], []\n",
            "    with torch.no_grad():\n",
            "        for images, labels in test_loader:\n",
            "            outputs = model(images.to(device))\n",
            "            probs = torch.softmax(outputs, dim=1)[:, 1].cpu().numpy()\n",
            "            _, preds = torch.max(outputs, 1)\n",
            "            all_preds.extend(preds.cpu().numpy())\n",
            "            all_labels.extend(labels.numpy())\n",
            "            all_probs.extend(probs)\n",
            "            \n",
            "    fps = measure_fps(model, test_loader, device)\n",
            "    params = count_parameters(model)\n",
            "    \n",
            "    return {\n",
            "        'name': name,\n",
            "        'history': history,\n",
            "        'preds': np.array(all_preds),\n",
            "        'labels': np.array(all_labels),\n",
            "        'probs': np.array(all_probs),\n",
            "        'fps': fps,\n",
            "        'params': params\n",
            "    }\n",
            "\n",
            "results = {}\n",
            "for m, name in [(hybrid_model, \"Hybrid CNN-QNN\"), (resnet, \"ResNet18\"), \n",
            "                (mobilenet, \"MobileNetV3\"), (efficientnet, \"EfficientNet-B0\")]:\n",
            "    results[name] = train_model(m, name, epochs=5)"
        ],
        "execution_count": None
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"\\nTraining YOLOv8n-cls...\")\n",
            "yolo_model = YOLO('yolov8n-cls.pt')\n",
            "yolo_res = yolo_model.train(data=DATA_DIR, epochs=5, imgsz=128, batch=32, device='0' if torch.cuda.is_available() else 'cpu', verbose=False)\n",
            "\n",
            "yolo_preds, yolo_probs, yolo_labels = [], [], []\n",
            "\n",
            "for img_path, label in zip(test_dataset.images, test_dataset.labels):\n",
            "    res = yolo_model(img_path, verbose=False)[0]\n",
            "    prob = res.probs.data[1].item() # Prob of weed (class 1)\n",
            "    pred = res.probs.top1\n",
            "    yolo_preds.append(pred)\n",
            "    yolo_probs.append(prob)\n",
            "    yolo_labels.append(label)\n",
            "\n",
            "# Measure YOLO FPS\n",
            "t = time.perf_counter()\n",
            "_ = yolo_model(test_dataset.images[:100], verbose=False)\n",
            "y_fps = 100 / (time.perf_counter() - t)\n",
            "\n",
            "results[\"YOLOv8n-cls\"] = {\n",
            "    'name': \"YOLOv8n-cls\",\n",
            "    'preds': np.array(yolo_preds),\n",
            "    'labels': np.array(yolo_labels),\n",
            "    'probs': np.array(yolo_probs),\n",
            "    'fps': y_fps,\n",
            "    'params': sum(p.numel() for p in yolo_model.parameters()),\n",
            "    'history': {'loss': [0]*5, 'acc': [0]*5}\n",
            "}"
        ],
        "execution_count": None
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "source": [
            "metrics_list = []\n",
            "for name, res in results.items():\n",
            "    acc = accuracy_score(res['labels'], res['preds'])\n",
            "    f1 = f1_score(res['labels'], res['preds'])\n",
            "    auc = roc_auc_score(res['labels'], res['probs'])\n",
            "    metrics_list.append({\n",
            "        'Model': name,\n",
            "        'Accuracy': acc,\n",
            "        'F1 Score': f1,\n",
            "        'AUC-ROC': auc,\n",
            "        'Parameters': res['params'],\n",
            "        'FPS': res['fps']\n",
            "    })\n",
            "\n",
            "df = pd.DataFrame(metrics_list)\n",
            "display(df)"
        ],
        "execution_count": None
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 1. Core Comparison Graphs\n",
            "Line graphs for training accuracy, and bar charts for FPS, Model Complexity, and Final Accuracy."
        ]
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "source": [
            "fig, axes = plt.subplots(2, 2, figsize=(16, 12))\n",
            "\n",
            "sns.barplot(data=df, x='Model', y='Accuracy', ax=axes[0, 0], palette='viridis')\n",
            "axes[0, 0].set_title(\"Model Accuracy Comparison\")\n",
            "axes[0, 0].tick_params(axis='x', rotation=45)\n",
            "\n",
            "sns.barplot(data=df, x='Model', y='FPS', ax=axes[0, 1], palette='rocket')\n",
            "axes[0, 1].set_title(\"Inference Speed (FPS)\")\n",
            "axes[0, 1].tick_params(axis='x', rotation=45)\n",
            "\n",
            "sns.barplot(data=df, x='Model', y='Parameters', ax=axes[1, 0], palette='mako')\n",
            "axes[1, 0].set_yscale('log')\n",
            "axes[1, 0].set_title(\"Model Complexity (Total Parameters)\")\n",
            "axes[1, 0].tick_params(axis='x', rotation=45)\n",
            "\n",
            "for name, res in results.items():\n",
            "    if name != \"YOLOv8n-cls\":\n",
            "        axes[1, 1].plot(res['history']['acc'], marker='o', label=name)\n",
            "axes[1, 1].set_title(\"Training Accuracy over Epochs\")\n",
            "axes[1, 1].set_xlabel(\"Epoch\")\n",
            "axes[1, 1].set_ylabel(\"Accuracy\")\n",
            "axes[1, 1].legend()\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ],
        "execution_count": None
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 2. Radar Chart\n",
            "Shows multivariate performance. A larger shape means a better overall model."
        ]
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "source": [
            "from math import pi\n",
            "\n",
            "categories = ['Accuracy', 'F1 Score', 'AUC-ROC', 'Speed (FPS)', 'Efficiency (1/Params)']\n",
            "N = len(categories)\n",
            "\n",
            "df_radar = df.copy()\n",
            "df_radar['Speed (FPS)'] = df['FPS'] / df['FPS'].max()\n",
            "df_radar['Efficiency (1/Params)'] = (1/df['Parameters']) / (1/df['Parameters']).max()\n",
            "\n",
            "angles = [n / float(N) * 2 * pi for n in range(N)]\n",
            "angles += angles[:1]\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(8, 8), subplot_kw=dict(polar=True))\n",
            "ax.set_theta_offset(pi / 2)\n",
            "ax.set_theta_direction(-1)\n",
            "plt.xticks(angles[:-1], categories)\n",
            "\n",
            "for i, row in df_radar.iterrows():\n",
            "    values = row[categories].values.flatten().tolist()\n",
            "    values += values[:1]\n",
            "    ax.plot(angles, values, linewidth=2, linestyle='solid', label=row['Model'])\n",
            "    ax.fill(angles, values, alpha=0.1)\n",
            "\n",
            "plt.legend(loc='upper right', bbox_to_anchor=(0.1, 0.1))\n",
            "plt.title(\"Radar Comparison of All Models\")\n",
            "plt.show()"
        ],
        "execution_count": None
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 3. ROC & Precision-Recall Curves\n",
            "Comparing True Positive Rates against False Positives."
        ]
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "source": [
            "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))\n",
            "\n",
            "for name, res in results.items():\n",
            "    fpr, tpr, _ = roc_curve(res['labels'], res['probs'])\n",
            "    ax1.plot(fpr, tpr, label=f\"{name} (AUC={roc_auc_score(res['labels'], res['probs']):.3f})\")\n",
            "    \n",
            "    prec, rec, _ = precision_recall_curve(res['labels'], res['probs'])\n",
            "    ax2.plot(rec, prec, label=name)\n",
            "\n",
            "ax1.plot([0, 1], [0, 1], 'k--')\n",
            "ax1.set_xlabel('False Positive Rate')\n",
            "ax1.set_ylabel('True Positive Rate')\n",
            "ax1.set_title('ROC Curves')\n",
            "ax1.legend()\n",
            "\n",
            "ax2.set_xlabel('Recall')\n",
            "ax2.set_ylabel('Precision')\n",
            "ax2.set_title('Precision-Recall Curves')\n",
            "ax2.legend()\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ],
        "execution_count": None
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 4. Confusion Matrices\n",
            "Side-by-side comparison of misclassifications."
        ]
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "source": [
            "fig, axes = plt.subplots(1, 5, figsize=(25, 5))\n",
            "\n",
            "for idx, (name, res) in enumerate(results.items()):\n",
            "    cm = confusion_matrix(res['labels'], res['preds'])\n",
            "    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[idx], cbar=False)\n",
            "    axes[idx].set_title(f\"{name}\\nConfusion Matrix\")\n",
            "    axes[idx].set_xlabel('Predicted')\n",
            "    axes[idx].set_ylabel('Actual')\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ],
        "execution_count": None
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 5. Model Agreement (Correlation Heatmap) & Critical Difference\n",
            "The heatmap shows how similarly the models make predictions. A score of 1.0 means they predicted the exact same classes on the test set."
        ]
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "source": [
            "preds_df = pd.DataFrame({name: res['preds'] for name, res in results.items()})\n",
            "plt.figure(figsize=(8, 6))\n",
            "sns.heatmap(preds_df.corr(), annot=True, cmap='coolwarm', vmin=0.5, vmax=1.0)\n",
            "plt.title(\"Model Prediction Agreement (Correlation Heatmap)\")\n",
            "plt.show()"
        ],
        "execution_count": None
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 6. SHAP Values (Feature Importance)\n",
            "Highlights which pixels drove the model's decision."
        ]
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"Computing SHAP values for Classical ResNet18 (as QNN gradients are unsupported by DeepExplainer)...\")\n",
            "background = next(iter(train_loader))[0][:100].to(device)\n",
            "test_images = next(iter(test_loader))[0][:5].to(device)\n",
            "\n",
            "e = shap.DeepExplainer(resnet, background)\n",
            "shap_values = e.shap_values(test_images)\n",
            "shap_numpy = [np.swapaxes(np.swapaxes(s, 1, -1), 1, 2) for s in shap_values]\n",
            "test_numpy = np.swapaxes(np.swapaxes(test_images.cpu().numpy(), 1, -1), 1, 2)\n",
            "\n",
            "shap.image_plot(shap_numpy, -test_numpy)"
        ],
        "execution_count": None
    }
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open("Benchmark_Multiple_SOTA.ipynb", "w") as f:
    json.dump(notebook, f, indent=2)

print("Created Benchmark_Multiple_SOTA.ipynb")
